name: fastotvlite
author: Alexandr Topilski <support@fastogt.com>
description: FastoTV Lite IPTV player.
homepage: https://fastotv.com
version: 1.13.7+32

publish_to: none

module:
  androidX: true

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  event_bus: ^2.0.0
  file_picker: ^3.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_tags: ^0.4.9+1
  get_it: ^6.0.0
  numberpicker: ^2.0.0
  shared_preferences: ^2.0.3
  unicorndial: ^1.1.5
  uuid: ^3.0.1

  dart_chromecast:
    git:
      url: https://github.com/fastogt/dart_chromecast.git
      ref: master
  fastotv_dart:
    git:
      url: https://gitlab.com/fastogt/fastotv_dart.git
      ref: master
  fastotv_device_info:
    git:
      url: https://gitlab.com/fastogt/fastotv_device_info.git
      ref: master
  flutter_fastotv_common:
    git:
      url: https://gitlab.com/fastogt/flutter_fastotv_common.git
      ref: master
  player:
    git:
      url: https://gitlab.com/fastogt/flutter_fastotv_player.git
      ref: main

dev_dependencies:
  dart_rules:
    git:
      url: https://github.com/fastogt/dart_rules.git
      ref: main
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - install/assets/
    - install/lang/
