name: fastotvlite
description: FastoTV Lite IPTV player.
homepage: https://fastotv.com
version: 1.13.8+33

publish_to: none

module:
  androidX: true

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  event_bus: ^2.0.0
  file_picker: ^4.3.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get_it: ^7.2.0
  numberpicker: ^2.1.1
  shared_preferences: ^2.0.13
  unicorndial: ^1.1.5
  uuid: ^3.0.5

  dart_chromecast:
    git:
      url: https://github.com/fastogt/dart_chromecast.git
      ref: master
  fastotv_dart:
    git:
      url: https://gitlab.com/fastogt/fastotv_dart.git
      ref: master
  fastotv_device_info:
    git:
      url: https://gitlab.com/fastogt/fastotv_device_info.git
      ref: master
  flutter_fastotv_common:
    git:
      url: https://gitlab.com/fastogt/flutter_fastotv_common.git
      ref: master
  player:
    git:
      url: https://gitlab.com/fastogt/flutter_fastotv_player.git
      ref: main

dev_dependencies:
  dart_rules:
    git:
      url: https://github.com/fastogt/dart_rules.git
      ref: main
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - install/assets/
    - install/lang/
